version: "3.9"

networks:
  cms-network:
    external: true

services:
  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: docker/wordpress/Dockerfile
    volumes:
      - ./var/www/html:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    env_file:
      - .env-wordpress
    networks:
      - cms-network
    restart: unless-stopped
    user: "1000:1000"

  wordpress_database:
    container_name: wordpress-database
    image: mariadb:latest
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
    env_file:
      - .env-wordpress-database
    networks:
      - cms-network
    restart: unless-stopped
    user: "1000:1000"

  caddy:
    image: caddy:2
    container_name: caddy
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - cms-network
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
