FROM php:8.2-fpm-alpine

RUN { \
    echo 'upload_max_filesize=64M'; \
    echo 'post_max_size=64M'; \
  } > /usr/local/etc/php/conf.d/uploads.ini

RUN \
  apt-get update -y && \
  apt-get install -y \
    git

RUN composer create-project dxpr/dxpr-marketing-cms-project:^10 ./
